### ISSUE TITLE
Allow users to specify their own web files like `package.json` and others used in `FrontendToolsManager`

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow-maven-plugin#17]
It is highly possible that some users would like to use their own files, at least to update the packages' versions.

**Comment by Legioth** [comment]
Could you please elaborate the use case?

**Comment by SomeoneToIgnore** [comment]
We have a [package.json](https://github.com/vaadin/flow-maven-plugin/blob/master/src/main/resources/package.json) used for dependency downloading.
If some security vulnerability pops up in any of the dependencies, it would be more beneficial for users to be able to upgrade it instantly.

**Comment by SomeoneToIgnore** [comment]
Issue moved to [vaadin/flow #3325](https://github.com/vaadin/flow/issues/3325) via [**ZenHub**](https://www.zenhub.com/)
