### ISSUE TITLE
DX test current version of bundling with Beverage Buddy

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-maven-plugin#35]
**Find out the pain points** in the current bundling workflow which makes the user to manually specify everything.

- Ask the user to bundle Beverage Buddy
- Ask the user to split the bundle into multiple _fragments_ so that when opening the `CategoriesList` and `ReviewsList` the unnecessary stuff from the other navigation target are not included

Have a meeting and discuss the next steps for improving the DX. Current follow up improvements are #19 and https://github.com/vaadin/flow/issues/2946

**Comment by SomeoneToIgnore** [comment]
The DX sessions are carried out.

DX plan: https://docs.google.com/document/d/1J6IYSAX2xAYsF9RXDu_LCXqrqHg7u57GhG26p1P4dHI

DX results: https://docs.google.com/document/d/1U4dzBeLXtZMLKsY0GAWgM8o9gMliSJ6FL7-EKXLFXpg
