### ISSUE TITLE
Enable bundling by default and use the new version in skeleton starter and beveragebuddy

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow-maven-plugin#43]
Users may want to test out the app before reading the documentation, we need to add bundling there so that they have better experience.

We should also add an info to the starters' README explaining on how they are able to create a production build.
 
We should
* set `enabled` property to true by default in the corresponding mojo
* release a new plugin
* update the plugin docs
* update the starters' poms and readmes

**Comment by Legioth** [comment]
I guess this would still only affect production builds? Running bundling every time I do `mvn jetty:run` would a quite bad exeprience.

**Comment by SomeoneToIgnore** [comment]
Yes, it will bundle every time only if you run `mvn jetty:run -PproductionMode`

**Comment by SomeoneToIgnore** [comment]
Issue moved to [vaadin/flow #3317](https://github.com/vaadin/flow/issues/3317) via [**ZenHub**](https://www.zenhub.com/)
