### ISSUE TITLE
Plugin release version depends on Flow snapshot version

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow-maven-plugin#45]
I have an issue with the plugin release version: it depends on Flow snapshot version.
So bakery app depends on Flow before global package rename (e.g. `HtmlImport` is `com/vaadin/ui/common/HtmlImport`).
And I should be able to use previous maven plugin version where `Htmlmport` is supposed to be in the required package (e.g. 0.0.5).
But I cannot use this version even though it correctly refers to the `Htmlmport`: it has dependency to Flow snapshot where `Htmlmport` has different package.

So to be able to use the maven plugin I need to have the most recent Flow version (as close to snapshot as possible). Actually I have to have snapshot version to make sure it works correctly.

May be maven plugin should not depend in Flow at all actually....... (not sure whether it's feasible).

**Comment by SomeoneToIgnore** [comment]
As discussed, the plugin will be moved to Flow monorepo to be released with the same version number as Flow.
This should fix the issue.

**Comment by pleku** [comment]
### Acceptance Criteria
- Move the `flow-maven-plugin` as a module build as last with Flow

**Comment by SomeoneToIgnore** [comment]
Have done everything except the last point: it makes more sense to update the plugin version after we enable bundling for the plugin by default.
